// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Relocator;

namespace Relocator.Migrations
{
    [DbContext(typeof(RelocatorContext))]
    partial class RelocatorContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Relocator.Models.States", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Altitude");

                    b.Property<int>("AveragePopulation");

                    b.Property<int>("AverageSalary");

                    b.Property<int>("AverageTemp");

                    b.Property<int>("GrowthRate");

                    b.Property<int>("ImgUrl");

                    b.Property<int>("Latitude");

                    b.Property<int>("Longitude");

                    b.Property<string>("StateName");

                    b.Property<int>("TaxRate");

                    b.HasKey("Id");

                    b.ToTable("States");
                });
#pragma warning restore 612, 618
        }
    }
}
